### ISSUE TITLE
sys.stdout has no attribute delegate

### ISSUE THREAD

**Issue by Tongsondub** [xmlrunner/unittest-xml-reporting#106]
I'm using xml-reporting to run our standard python unittest suite. The tests themselves run perfectly fine all the way to the end but then we get an exception when it goes on to output the xml. 

Any ideas on how we get around this or if there is a fix for it? We are running Python 2.7.6 on Ubuntu 14.04 if that matters.

This is the full full exception we see(snipped the html portion of the output):
```
Ran 2463 tests in 132.803s

OK

Generating XML reports...
..........html snipped...........

<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "./full_test.py", line 48, in &lt;module&gt;
    xmlrunner.XMLTestRunner(output=file('./test-reports/report.xml', 'w')).run(testRun.getTestSuite())
  File "build/bdist.linux-x86_64/egg/xmlrunner/xmlrunner.py", line 468, in run
    self._restore_standard_output()
  File "build/bdist.linux-x86_64/egg/xmlrunner/xmlrunner.py", line 397, in _restore_standard_output
    sys.stdout = sys.stdout.delegate
AttributeError: 'file' object has no attribute 'delegate'

-->

```

**Comment by Tongsondub** [comment]
NVM, somehow I have multiple versions of this package. Cleaned them all up and installed latest and everything is working now.
