### ISSUE TITLE
xmlrunner does not print out the supplied subTest parameter

### ISSUE THREAD

**Issue by shabzy** [xmlrunner/unittest-xml-reporting#155]
When doing a subTest in unittest:
`with self.subTest(num=i):`
The "num=i" parameter is supposed to be printed out in the test debug:
When I run without xmlrunner, i get:
```
#!/usr/bin/python3

import random
import unittest
import xmlrunner

class NumbersTest(unittest.TestCase):
    def test_even(self):
        """
        Test that numbers between 0 and 5 are all even.
        """
        for i in range(0, 6):
            with self.subTest(num=i):
                self.assertEqual(i % 2, 0)

if __name__ == '__main__':
    unittest.main()
```

Output:
```
======================================================================
FAIL: test_even (__main__.NumbersTest) (num=3)
----------------------------------------------------------------------
```

Note the **(num=3)**

With xmlrunner:
```
#!/usr/bin/python3

import random
import unittest
import xmlrunner

class NumbersTest(unittest.TestCase):

    def test_even(self):
        """
        Test that numbers between 0 and 5 are all even.
        """
        for i in range(0, 6):
            with self.subTest(num=i):
                self.assertEqual(i % 2, 0)

if __name__ == '__main__':
    unittest.main(
        testRunner=xmlrunner.XMLTestRunner(output='test-reports'),
        # these make sure that some options that are not applicable
        # remain hidden from the help menu.
        failfast=False, buffer=False, catchbreak=False)`
```
Output:
```
======================================================================
ERROR [0.002s]: test_even (__main__.NumbersTest)
----------------------------------------------------------------------
```
Note that there is no (num=3).  The subTest() info inside brackets is lost.

The unittest source (unittest/case.py):

class _SubTest has a method
def _subDescription(self):

Which is used to append the passed-in info
I think xmlrunner is maybe not using that properly to get the full desc.

I believe this is quite an important as when running with multiple parameters, you cannot actually tell which parameter failed, thereby making the subTest error useless.

**Comment by henrywah196** [comment]
nice if this can be fix asap.

**Comment by XonqNopp** [comment]
Plus the test is reported as ERROR when it should be FAIL

**Comment by XonqNopp** [comment]
Just opened PR #178

**Comment by dnozay** [comment]
```
$ ./.tox/py37/bin/python foo.py 

Running tests...
----------------------------------------------------------------------
F
======================================================================
FAIL [0.000s]: test_even (__main__.NumbersTest) (num=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "foo.py", line 15, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL [0.000s]: test_even (__main__.NumbersTest) (num=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "foo.py", line 15, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL [0.007s]: test_even (__main__.NumbersTest) (num=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "foo.py", line 15, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (failures=3)

Generating XML reports...
Generated XML report: test-reports/TEST-NumbersTest-20190316161446.xml
```
