### ISSUE TITLE
ImportError: cannot import name TextTestRunner

### ISSUE THREAD

**Issue by YaruTsai** [xmlrunner/unittest-xml-reporting#162]
I have installed the unittest-xml-reporting in my virtualenv (python2 and python3). Then, I use the example code to execute in my environment. But it shows the error message.

$pip install unittest-xml-reporting
$python unittest.py

(unittest_p2_env) CherryAir:unittest_xml_reporting Apple$ python unittest.py 
Traceback (most recent call last):
  File "unittest.py", line 2, in <module>
    import unittest
  File "/Users/Apple/Python/unittest_code/unittest_xml_reporting/unittest.py", line 3, in <module>
    import xmlrunner
  File "/Users/Apple/Python/env/unittest_p2_env/lib/python2.7/site-packages/xmlrunner/__init__.py", line 11, in <module>
    from .runner import XMLTestRunner
  File "/Users/Apple/Python/env/unittest_p2_env/lib/python2.7/site-packages/xmlrunner/runner.py", line 5, in <module>
    from .unittest import TextTestRunner
  File "/Users/Apple/Python/env/unittest_p2_env/lib/python2.7/site-packages/xmlrunner/unittest.py", line 7, in <module>
    from unittest import TextTestRunner
ImportError: cannot import name TextTestRunner

**Comment by dnozay** [comment]
Not enough info to debug.
