### ISSUE TITLE
(v2.4.0) AttributeError if used with ConcurrentTestSuite

### ISSUE THREAD

**Issue by pasoroki** [xmlrunner/unittest-xml-reporting#189]
Hello,
we just hit interesting bug with unittest-xml-reporting-2.4.0 if unittests are running with ConcurrentTestSuite.
In such case tests are failed to run and XMLTestRunner reports success in any case

Failure case:
```
$ ./venv/bin/pip freeze
concurrencytest==0.1.2
extras==1.0.0
fixtures==3.0.0
linecache2==1.0.0
pbr==5.1.3
python-mimeparse==1.6.0
python-subunit==1.3.0
six==1.12.0
testtools==2.3.0
traceback2==1.4.0
unittest-xml-reporting==2.4.0
unittest2==1.1.0

[issue.tar.gz](https://github.com/xmlrunner/unittest-xml-reporting/files/2990280/issue.tar.gz)

$ ./venv/bin/python3 unittest_run.py tests/test_simple.py

SUITE:
<unittest.suite.TestSuite tests=[<unittest.loader._FailedTest testMethod=tests/test_simple>]>

Creating Concurrent Test Suite
Triggering tests

Running tests...
----------------------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testsuite.py", line 106, in _run_test
    test.run(process_result)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/__init__.py", line 1197, in run
    protocol.lineReceived(line)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/__init__.py", line 567, in lineReceived
    self._state.lineReceived(line)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/__init__.py", line 404, in lineReceived
    self.details_parser.lineReceived(line)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/details.py", line 42, in lineReceived
    self._state.endDetails()
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/__init__.py", line 399, in endDetails
    self._report_outcome()
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/subunit/__init__.py", line 441, in _report_outcome
    details=self.details_parser.get_details())
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1372, in addError
    return self.decorated.addError(test, details=details)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1248, in addError
    self.result.addError, test, err, details=details)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1231, in _add_result_with_semaphore
    self.result.startTest(test)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1508, in startTest
    return self.decorated.startTest(test)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/xmlrunner/result.py", line 271, in startTest
    test_method = getattr(test, test._testMethodName)
AttributeError: 'RemotedTestCase' object has no attribute '_testMethodName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testsuite.py", line 112, in _run_test
    case.run(process_result)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testcase.py", line 857, in run
    outcome(self, details=self._details)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1372, in addError
    return self.decorated.addError(test, details=details)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1248, in addError
    self.result.addError, test, err, details=details)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1231, in _add_result_with_semaphore
    self.result.startTest(test)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/testtools/testresult/real.py", line 1508, in startTest
    return self.decorated.startTest(test)
  File "/private/tmp/tst/venv/lib/python3.7/site-packages/xmlrunner/result.py", line 271, in startTest
    test_method = getattr(test, test._testMethodName)
AttributeError: 'PlaceHolder' object has no attribute '_testMethodName'


----------------------------------------------------------------------
Ran 2 tests in 0.016s

OK

Generating XML reports...
Success
```

Correct behavior if we switch back to 2.3.2
```
$ ./venv/bin/pip install unittest-xml-reporting==2.3.2
$ ./venv/bin/pip freeze
concurrencytest==0.1.2
extras==1.0.0
fixtures==3.0.0
linecache2==1.0.0
pbr==5.1.3
python-mimeparse==1.6.0
python-subunit==1.3.0
six==1.12.0
testtools==2.3.0
traceback2==1.4.0
unittest-xml-reporting==2.3.2
unittest2==1.1.0

$ ./venv/bin/python3 unittest_run.py tests/test_simple.py

SUITE:
<unittest.suite.TestSuite tests=[<unittest.loader._FailedTest testMethod=tests/test_simple>]>

Creating Concurrent Test Suite
Triggering tests

Running tests...
----------------------------------------------------------------------
  unittest.loader._FailedTest.tests/test_simple (subunit.RemotedTestCase)
unittest.loader._FailedTest.tests/test_simple ... ERROR (0.001s)

======================================================================
ERROR [0.001s]: unittest.loader._FailedTest.tests/test_simple (subunit.RemotedTestCase)
unittest.loader._FailedTest.tests/test_simple
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
ImportError: Failed to import test module: tests/test_simple
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests/test_simple'


----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)

Generating XML reports...
Generated XML report: test-reports/TEST-subunit.RemotedTestCase-20190320145231.xml
Failure
```

Attached `issue.tar.gz` is a test case that I created

**Comment by pasoroki** [comment]
[issue.tar.gz](https://github.com/xmlrunner/unittest-xml-reporting/files/2990285/issue.tar.gz)

**Comment by dnozay** [comment]
```
>>> class T(unittest.TestCase):
...    def test_foo():
...       pass
... 
>>> t = T('test_foo')
>>> t._testMethodName
'test_foo'
>>> class RemotedTestCase(unittest.TestCase):
...     def __init__(self, description):
...         """Create a psuedo test case with description description."""
...         self.__description = description
... 
>>> t = RemotedTestCase('test_foo')
>>> t._testMethodName
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RemotedTestCase' object has no attribute '_testMethodName'
```

`subunit` does not call `super()` so
