### ISSUE TITLE
"Generated XML report" output does not obey verbosity

### ISSUE THREAD

**Issue by rpkilby** [xmlrunner/unittest-xml-reporting#191]
Hi. #179 doesn't seem to obey the verbosity setting. When running the test suite locally, all of the useful test output is immediately drowned out by the "Generated XML report:" output. This is especially annoying when you have consecutive test runs - you need to scroll up and down a lot of repetitive output to try and find the actual test output.

I'm not sure if this output should be included at verbosity level 1 or 2, but it should at least be disabled at level 0. For now, I'm simply pinning xmlrunner to an older version.

<details>
<summary>Sample output:</summary>

```shell
(.venv) Sherpa:django-filter bagel$ tox -e py37-django21
GLOB sdist-make: /Users/bagel/Documents/projects/django-filter/setup.py
py37-django21 inst-nodeps: /Users/bagel/Documents/projects/django-filter/.tox/.tmp/package/1/django-filter-2.1.0.zip
py37-django21 installed: certifi==2019.3.9,chardet==3.0.4,coreapi==2.3.3,coreschema==0.0.4,coverage==4.5.3,Django==2.1.7,django-crispy-forms==1.7.2,django-filter==2.1.0,djangorestframework==3.9.2,idna==2.8,itypes==1.1.0,Jinja2==2.10,Markdown==2.6.4,MarkupSafe==1.1.1,mock==2.0.0,pbr==5.1.3,pytz==2018.9,requests==2.21.0,six==1.12.0,unittest-xml-reporting==2.5.0,uritemplate==3.0.0,urllib3==1.24.1
py37-django21 run-test-pre: PYTHONHASHSEED='961049855'
py37-django21 runtests: commands[0] | coverage run --parallel-mode --source django_filters ./runtests.py --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

Running tests...
----------------------------------------------------------------------
................................................................................................................s..x...F....ss..x..x..................................................................................................................................................................................................................E................s....................sss.............................................................................................................
======================================================================
ERROR [0.001s]: test_meta_fields_containing_unknown_fields (tests.test_filterset.FilterSetClassCreationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bagel/Documents/projects/django-filter/tests/test_filterset.py", line 447, in test_meta_fields_containing_unknown_fields
    with self.assertRaises(TypeError, msg):
AttributeError: __enter__

======================================================================
FAIL [0.005s]: test_filtering (tests.test_filtering.IsoDateTimeFromToRangeFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bagel/Documents/projects/django-filter/tests/test_filtering.py", line 1005, in test_filtering
    self.assertEqual(len(results.qs), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 492 tests in 1.496s

FAILED (failures=1, errors=1, skipped=7, expected failures=3)

Generating XML reports...
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.AutoFilterSetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.GetFilterClassTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.GetSchemaFieldsTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.RenamedBackendAttributesTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.RenamedViewSetAttributesTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.TemplateTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_backends.ValidationErrorTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_filters.BooleanFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_filters.ModuleImportTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_filterset.CrispyFormsCompatTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_filterset.FilterSetFilterForFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_integration.DjangoFilterOrderingTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_integration.IntegrationTestDetailFiltering-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.rest_framework.test_integration.IntegrationTestFiltering-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_conf.DefaultSettingsTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_conf.IsCallableTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_conf.OverrideSettingsTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.BaseCSVFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.BaseRangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.DateRangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.DateTimeRangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.IsoDateTimeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.IsoDateTimeRangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.LookupChoiceFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.LookupTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.RangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_fields.TimeRangeFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.AllValuesFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.AllValuesMultipleFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.BooleanFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.CSVFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.CSVRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.CharFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.ChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DateFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DateFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DateRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DateTimeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DateTimeFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.DurationFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.FKRelationshipTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.FilterMethodTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.IntegerFilterTest-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.LookupChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.M2MRelationshipTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.MiscFilterSetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.ModelChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.ModelMultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.MultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.NonSymmetricalSelfReferentialRelationshipTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.NumberFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.O2ORelationshipTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.OrderingFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.RangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.SymmetricalSelfReferentialRelationshipTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.TimeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.TimeRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.TransformedQueryExpressionFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.TypedMultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.AllValuesFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.BaseInFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.BaseRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.BooleanFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.CSVFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.CharFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.ChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DateFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DateFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DateRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DateTimeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DateTimeFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.DurationFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.FilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.IsoDateTimeFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.LookupChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.ModelChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.ModelMultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.ModuleImportTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.MultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.NumberFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.NumericRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.OrderingFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.RangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.TimeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.TimeRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.TypedMultipleChoiceFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filters.UUIDFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.DbFieldDefaultFiltersTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterMethodTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetClassCreationTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetFilterForFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetFilterForLookupTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetFilterForReverseFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetInstantiationTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.FilterSetQuerysetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.MiscFilterSetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.ReverseFilterSetFilterForFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_forms.FilterSetFormTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_forms.FilterSetValidityTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_groups.FilterGroupTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_groups.ModuleImportTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.GetFieldPartsTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.GetModelFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.HandleTimezone-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.LabelForFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.MigrationNoticeTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.RenameAttributesBaseTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.ResolveFieldTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.TranslateValidationDataTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.VerboseFieldNameTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_utils.VerboseLookupExprTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_views.GenericClassBasedViewTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_views.GenericFunctionalViewTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.BooleanWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.CSVSelectTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.CSVWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.LinkWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.LookupTypeWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.QueryArrayWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.RangeWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_widgets.SuffixedMultiWidgetTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filtering.IsoDateTimeFromToRangeFilterTests-20190321234648.xml
Generated XML report: .xmlcoverage/TEST-tests.test_filterset.HelperMethodsTests-20190321234648.xml
Destroying test database for alias 'default'...
ERROR: InvocationError for command '/Users/bagel/Documents/projects/django-filter/.tox/py37-django21/bin/coverage run --parallel-mode --source django_filters ./runtests.py --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner' (exited with code 1)
_____________________________________________________ summary _____________________________________________________
ERROR:   py37-django21: commands failed

```
</details>

**Comment by rpkilby** [comment]
Just a quick followup, I assume this should be enabled at verbosity level 2. If you set verbosity to 0, then you also lose the per-test `.` output.

**Comment by rpkilby** [comment]
Many thanks. I assume `showAll` is equivalent to `verbosity=2`?
