### ISSUE TITLE
XML Runner does not create xml report if unittest.subtest in test suite. Throws AttributeError: '_SubTest' object has no attribute 'elapsed_time'

### ISSUE THREAD

**Issue by vvargova** [xmlrunner/unittest-xml-reporting#218]
I have som unittest.subtest in my testSuite but when I run testSuite via xmlrunner.XMLTestRunner(verbosity=2, output=output_path).run(testSuite) I get error:

Traceback (most recent call last):
  File "C:\Program Files\Python 3.7\lib\site-packages\xmlrunner\xmlrunner.py", line 421, in run
    result.printErrors()
  File "C:\Program Files\Python 3.7\lib\unittest\runner.py", line 110, in printErrors
    self.printErrorList('FAIL', self.failures)
  File "C:\Program Files\Python 3.7\lib\site-packages\xmlrunner\xmlrunner.py", line 217, in printErrorList
    '%s [%.3fs]: %s' % (flavour, test_info.elapsed_time,
AttributeError: '_SubTest' object has no attribute 'elapsed_time'

**Comment by hasslercastro** [comment]
Did you manage to fix it?

**Comment by hasslercastro** [comment]
If someone find this issue, the problem was, that there is a naming confliction between xmlrunner packages,

The solution was removing **xmlrunner** and installing **unittest-xml-reporting**
