### ISSUE TITLE
relpath fails when running in Azure DevOps on Windows

### ISSUE THREAD

**Issue by denravonska** [xmlrunner/unittest-xml-reporting#222]
I have an Azure pipeline which does unit tests and reports the results as a JUnit XML file. This works fine in Linux but on Windows I get this:

```
2020-04-02T09:35:34.8222263Z ----------------------------------------------------------------------
2020-04-02T09:35:34.8223241Z Ran 1 test in 0.000s
2020-04-02T09:35:34.8223794Z 
2020-04-02T09:35:34.8224274Z FAILED (errors=1)
2020-04-02T09:35:34.8224517Z 
2020-04-02T09:35:34.8224774Z Generating XML reports...
2020-04-02T09:35:34.8225151Z Traceback (most recent call last):
2020-04-02T09:35:34.8225762Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\runpy.py", line 193, in _run_module_as_main
2020-04-02T09:35:34.8226432Z     "__main__", mod_spec)
2020-04-02T09:35:34.8226970Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\runpy.py", line 85, in _run_code
2020-04-02T09:35:34.8227463Z     exec(code, run_globals)
2020-04-02T09:35:34.8228156Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\__main__.py", line 19, in <module>
2020-04-02T09:35:34.8228761Z     XMLTestProgram(module=None)
2020-04-02T09:35:34.8229536Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\runner.py", line 125, in __init__
2020-04-02T09:35:34.8230267Z     super(XMLTestProgram, self).__init__(*args, **kwargs)
2020-04-02T09:35:34.8230647Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\unittest\main.py", line 95, in __init__
2020-04-02T09:35:34.8231156Z     self.runTests()
2020-04-02T09:35:34.8231498Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\runner.py", line 178, in runTests
2020-04-02T09:35:34.8231871Z     super(XMLTestProgram, self).runTests()
2020-04-02T09:35:34.8232222Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\unittest\main.py", line 256, in runTests
2020-04-02T09:35:34.8232568Z     self.result = testRunner.run(self.test)
2020-04-02T09:35:34.8232939Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\runner.py", line 112, in run
2020-04-02T09:35:34.8233286Z     result.generate_reports(self)
2020-04-02T09:35:34.8233685Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\result.py", line 633, in generate_reports
2020-04-02T09:35:34.8234095Z     suite_name, tests, doc, parentElement, self.properties
2020-04-02T09:35:34.8234553Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\result.py", line 510, in _report_testsuite
2020-04-02T09:35:34.8235002Z     _XMLTestResult._report_testcase(test, testsuite, xml_document)
2020-04-02T09:35:34.8235430Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\xmlrunner\result.py", line 556, in _report_testcase
2020-04-02T09:35:34.8235829Z     filename = os.path.relpath(test_result.filename)
2020-04-02T09:35:34.8236194Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py", line 584, in relpath
2020-04-02T09:35:34.8236502Z     path_drive, start_drive))
2020-04-02T09:35:34.8236775Z ValueError: path is on mount 'C:', start on mount 'D:'
```

Maybe catch this error and fall back to absolute paths?

**Comment by dnozay** [comment]
https://bugs.python.org/issue7195

```
        if test_result.filename is not None:
            # Try to make filename relative to current directory.
            filename = os.path.relpath(test_result.filename)
```

```
2020-04-02T09:35:34.8236775Z ValueError: path is on mount 'C:', start on mount 'D:'
```
- your current dir is somewhere on `C:` when you run the tests as opposed to where the test files are, which seems to be somewhere in `D:`

accepting PRs... I'll work on this when I get some free time.

**Comment by svaningelgem** [comment]
I had the same issue.
Changed the lines above into:
```
            # Try to make filename relative to current directory.
            try:
                filename = os.path.relpath(test_result.filename)
            except ValueError:
                if platform.system() != 'Windows':
                    raise
                filename = test_result.filename
````

Works fine for me now. Dunno what I broke though ;-)
