### ISSUE TITLE
AttributeError in result._save_output_data

### ISSUE THREAD

**Issue by clementmangin** [xmlrunner/unittest-xml-reporting#83]
I'm facing the following exception when executing my tests:

```
  File "ve/lib/python2.7/site-packages/django/test/runner.py", line 115, in run_suite
    ).run(suite)
  File "ve/lib/python2.7/site-packages/xmlrunner/runner.py", line 59, in run
    test(result)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "ve/lib/python2.7/site-packages/django/test/testcases.py", line 184, in __call__
    result.addError(self, sys.exc_info())
  File "ve/lib/python2.7/site-packages/xmlrunner/result.py", line 207, in addError
    self._save_output_data()
  File "ve/lib/python2.7/site-packages/xmlrunner/result.py", line 164, in _save_output_data
    self._stdout_data = sys.stdout.getvalue()
AttributeError: 'file' object has no attribute 'getvalue'
```

**Comment by phyng** [comment]
+1

~~~text
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/phyng/dev/env_bazaar/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/phyng/dev/env_bazaar/site-packages/django/test/runner.py", line 211, in run_tests
    result = self.run_suite(suite)
  File "/home/phyng/dev/env_bazaar/site-packages/xmlrunner/extra/djangotestrunner.py", line 38, in run_suite
    output=output, failfast=self.failfast).run(suite)
  File "/home/phyng/dev/env_bazaar/site-packages/xmlrunner/runner.py", line 59, in run
    test(result)
  File "/opt/pypy/lib-python/2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/opt/pypy/lib-python/2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/phyng/dev/env_bazaar/site-packages/django/test/testcases.py", line 186, in __call__
    super(SimpleTestCase, self).__call__(result)
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/opt/pypy/lib-python/2.7/unittest/case.py", line 372, in run
  File "/home/phyng/dev/env_bazaar/site-packages/xmlrunner/result.py", line 196, in stopTest
    self._save_output_data()
  File "/home/phyng/dev/env_bazaar/site-packages/xmlrunner/result.py", line 189, in _save_output_data
    self._stdout_data = sys.stdout.getvalue()
AttributeError: 'file' object has no attribute 'getvalue'
~~~

settings.py

~~~python
TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
~~~

**Comment by tkanemoto** [comment]
+1
I'm also getting this error if the test fails during setup and sys.stdout and sys.stderr have not been reassigned yet.

**Comment by dnozay** [comment]
Would be nice to add a testcase to reproduce the issue so that we have regression testing after we add a fix.

**Comment by tkanemoto** [comment]
I've added a test case for this now.
